ignore:
    - "src/main/kotlin/io/github/marioalvial/ze/delivery/challenge/ChallengeApplication.kt"
    - "src/main/kotlin/io/github/marioalvial/ze/delivery/challenge/partner/application/*Routes.kt"
    - "src/main/kotlin/io/github/marioalvial/ze/delivery/challenge/config"

codecov:
    notify:
        wait_for_ci: no
